### ISSUE TITLE
proposal for versioning

### ISSUE THREAD

**Issue by matthewleon** [purescript/package-sets#105]
Instead of `psc-0.11.6` and `psc-0.11.6-prime`, how about adding another dot in, `psc-0.11.x.y`? I imagine that updated package sets for a given compiler release might become a more regular thing as the compiler reaches stability.

**Comment by paf31** [comment]
I was also thinking of just naming them based on the date, like Stackage has nightly builds.

**Comment by joneshf** [comment]
Yeah, I've been doing a date based thing: https://github.com/joneshf/purescript-package-sets/releases. It's working pretty well.

**Comment by f-f** [comment]
This has been implemented since [this release](https://github.com/purescript/package-sets/releases/tag/psc-0.11.6-09272017), so I'll close
