### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by artemisSystem** [purescript/package-sets#1089]

**Comment by thomashoneyman** [comment]
https://github.com/purescript/package-sets/tree/psc-0.14.7-20220418

**Comment by artemisSystem** [comment]
Thanks!

One question, why is it for `0.14.7` and not `0.14.9`? I know it doesn't matter, so i'm just curious

**Comment by thomashoneyman** [comment]
It's just that the release script here hasn't yet been updated to note the latest compiler release is 0.14.9. An oversight! But it doesn't hurt anything, as you noted.
