### ISSUE TITLE
Add contrib and node libraries

### ISSUE THREAD

**Issue by paf31** [purescript/package-sets#11]
**Contrib**
- [x] purescript-argonaut-codecs
- [x] purescript-coroutines
- [x] purescript-nullable
- [x] purescript-argonaut-core
- [x] purescript-strongcheck
- [x] purescript-machines
- [x] purescript-arraybuffer-types
- [x] purescript-media-types
- [x] purescript-http-methods
- [x] purescript-these
- [x] purescript-js-timers
- [x] purescript-js-date
- [x] purescript-now
- [x] purescript-profunctor-lenses
- [x] purescript-dom
- [x] purescript-argonaut
- [x] purescript-argonaut-traversals
- [x] purescript-options
- [x] purescript-freet
- [x] [purescript-foreign-lens](https://github.com/purescript-contrib/purescript-foreign-lens)
- [x] [purescript-aff-coroutines](https://github.com/purescript-contrib/purescript-aff-coroutines)
- [x] [purescript-react](https://github.com/purescript-contrib/purescript-react)
- [x] [purescript-jquery](https://github.com/purescript-contrib/purescript-jquery)
- [x] [purescript-canvas](https://github.com/purescript-contrib/purescript-canvas)
- [x] [purescript-unicode](https://github.com/purescript-contrib/purescript-unicode)
- [x] [purescript-sammy](https://github.com/purescript-contrib/purescript-sammy)
- [x] [purescript-handlebars](https://github.com/purescript-contrib/purescript-handlebars)
- [x] [purescript-parsing](https://github.com/purescript-contrib/purescript-parsing)
- [x] [purescript-drawing](https://github.com/purescript-contrib/purescript-drawing)
- [x] [purescript-react-dom](https://github.com/purescript-contrib/purescript-react-dom)
- [x] [purescript-form-urlencoded](https://github.com/purescript-contrib/purescript-form-urlencoded)
- [ ] [purescript-react-addons-css-transition-group](https://github.com/purescript-contrib/purescript-react-addons-css-transition-group)
- [x] [purescript-string-parsers](https://github.com/purescript-contrib/purescript-string-parsers)
- [ ] [purescript-base](https://github.com/purescript-contrib/purescript-base)
- [ ] [purescript-http-headers](https://github.com/purescript-contrib/purescript-http-headers)
- [ ] [purescript-lens](https://github.com/purescript-contrib/purescript-lens)

**Node**
- [x] purescript-node-fs-aff
- [x] purescript-posix-types
- [x] purescript-node-fs
- [x] purescript-node-buffer
- [x] purescript-node-streams
- [x] purescript-node-http
- [x] purescript-node-child-process
- [x] purescript-node-process
- [x] purescript-node-readline
- [x] purescript-node-path
- [x] purescript-node-url

**Comment by paf31** [comment]
cc @jazonzolatz @jdegoes @joneshf @garyb Could you please update your contrib libraries (form-urlencoded, react-addons-css-transition-group, base, http-headers and lens), and ideally add package info here? Thanks!

**Comment by jdegoes** [comment]
Can you please delete `base`? We need something more like Stack.

**Comment by paf31** [comment]
Maybe just move it to `purescript-deprecated` then?

**Comment by paf31** [comment]
Although I still think it serves a nice purpose, which is to collect lots of common imports into `import Base`.

**Comment by joneshf** [comment]
Unless you have a compelling reason for wanting `purescript-lens`, I'd like to deprecate that library as well. Ideally renaming `purescript-profunctor-lenses` to `purescript-lens` at the same time.

**Comment by jasonzoladz** [comment]
will do

**Comment by zudov** [comment]
#26

**Comment by jasonzoladz** [comment]
Done.

**Comment by paf31** [comment]
@jasonzoladz Can I add `purescript-react-addons-css-transition-group` to `packages.json` then? (or if you'd like to send a PR, that'd be great too.. 😄)

**Comment by paf31** [comment]
I'm happy to call this done at this point.
