### ISSUE TITLE
Automate release on merge to `master`

### ISSUE THREAD

**Issue by ptrfrncsmrph** [purescript/package-sets#1147]
Based on a discussion in the Discord, it was suggested to open an issue: https://discord.com/channels/864614189094928394/865396398606254100/977930898265743430

I'm not very familiar with GitHub Actions API, but it seems like we could automate publishing a release whenever a PR is merged to `master`.

**Comment by ptrfrncsmrph** [comment]
Per the [release guide](https://github.com/purescript/package-sets/blob/master/RELEASE_GUIDE.md), there's some coordination that needs to happen with other repos ([`purescript/purescript-metadata`](https://github.com/purescript/purescript-metadata) and [`justinwoo/easy-purescript-nix`](https://github.com/justinwoo/easy-purescript-nix)) as part of the release process that doesn't seem easy or possible to automate. 

Maybe it would be possible to still do those steps manually (when there's a new version of PureScript) and automate running the [`release.sh`](https://github.com/purescript/package-sets/blob/master/release.sh) script on merge to `master`?

**Comment by mhmdanas** [comment]
Opening a PR on every merge to `master` is a bit too often, don't you think? I think having a cap of one release per 1-3 days is a good idea.

**Comment by ptrfrncsmrph** [comment]
> Opening a PR on every merge to `master`

As I understand it, I don't think automating the release would require opening a PR or anything that would require manual input. I'm not sure what possible downsides there would be of having more frequent releases—maybe rate-limiting, if that applies?

**Comment by mhmdanas** [comment]
Ah, sorry, I meant "creating a release on every merge to `master`," not "creating a PR on every merge to `master`." Other than that, my point is the same.

**Comment by f-f** [comment]
The [alpha for the new Registry](https://discourse.purescript.org/t/registry-alpha-launched/3146) has now launched, and this entails the automation of this repository - packages in the set will be managed through [the new API](https://github.com/purescript/registry#modify-the-package-set), and a new release will be cut once a day if there are any new updates.

I believe this solves this issue, but please open an issue in the [`registry-dev` repo](https://github.com/purescript/registry-dev) if not.
