### ISSUE TITLE
Needs some docs on how to add a package to the set

### ISSUE THREAD

**Issue by justinwoo** [purescript/package-sets#117]
With the new `verify` command, the workflow for updating and validating a package set is pretty easy, but this needs to actually be written down somewhere how it works. Probably information should live either in this repo or in the section in the README of psc-package.

Anyone with opinions about where it *should* go? I feel like it's easier to read when it's here already while you have this repo checked out to prepare a package set.

**Comment by paf31** [comment]
Let's add docs to psc-package, and link to it here?
