### ISSUE TITLE
easy-ffi

### ISSUE THREAD

**Issue by CGenie** [purescript/package-sets#1218]
Hello,

https://github.com/pelotom/purescript-easy-ffi/blob/master/packages.dhall

It seems that `easy-ffi` is compatible with at least 0.15.0. Could we add it to the package sets?

**Comment by thomashoneyman** [comment]
Looks like it was commented out during the 0.15 release and never re-added:
https://github.com/purescript/package-sets/blob/54980addb5bf2f274e4be26b98b3e6b1037fda3f/src/groups/pelotom.dhall

I can give it a shot re-adding it.

**Comment by thomashoneyman** [comment]
The 0.15-compatible release of this library has not had a tagged release, so we can't add it. Once there is a Git tag pointing to the release we can process the change.

**Comment by lfarroco** [comment]
I created a tagged release in my fork https://github.com/lfarroco/purescript-easy-ffi. The situation is unusual - I don't know what the practice is for abandoned repos.

**Comment by thomashoneyman** [comment]
If a repo is abandoned then you can register a fork, but it must be under a new name. We don’t transfer names for security reasons.

If you just need to rely on this project in your application, then I’d suggest adding an override in your spago.dhall file to point to the commit you want (or to your fork).

However, if you plan to maintain this library for the long haul then you can fork it to a new name and register it.

**Comment by lfarroco** [comment]
@CGenie the package `small-ffi` should be available in the latest package-set - it has the same API as `easy-ffi`

@thomashoneyman thanks for the help on getting this merged!
