### ISSUE TITLE
Tag automatically

### ISSUE THREAD

**Issue by joneshf** [purescript/package-sets#128]
CI checks each PR that the set still works. But tagging is still a manual process and lags behind changes. Can we make it so every merge to master creates a tag?

**Comment by paf31** [comment]
Well a SHA hash is that, effectively, right? :)

Every merge seems a bit much perhaps, but I'd be fine with creating daily or weekly tags.

**Comment by paf31** [comment]
I do think this sounds like a good idea though.

**Comment by joneshf** [comment]
I can't seem to get `psc-package` to work with a SHA in `psc-package.json`.

At first glance it sounds a bit overkill to push a tag for every merge to `master`. In practice, it's less than it sounds. A daily or weekly tag would be nice in the sense of consistency. But, I think a daily or weekly tag doesn't really suit the frequency of changes in this repo or the concept of `psc-package` as it is right now.

The majority of commits to `master` come at an infrequent pace: https://github.com/purescript/package-sets/graphs/commit-activity. There are many days when nothing happens. And a few weeks when nothing happens. Since the beginning of the year, the vast majority of merges happen on separate days.

I think a daily or weekly tag is fine for something like stackage where the volume of packages changing per day is high: https://www.stackage.org/diff/nightly-2017-11-24/nightly-2017-11-25 and you also don't have to maintain a fork of stackage to have a dependency not in the set.

As it sits now, we'd be asking someone to maintain a fork of this repo for either a day or a week before they can use their dependency seamlessly. I'm also aware that's basically the status quo, but I think pushing a tag immediately can improve the status quo for contributors.

**Comment by paf31** [comment]
I do think SHA support is the correct fix for this though, and it is coming (there is a PR open on `psc-package` now).

You're right that daily or weekly tags don't really solve the problem. I think they do solve a different problem, so maybe we can do that anyway. In any case, it would be good to try to do what we're doing now, but on a schedule instead of whenever we accrete enough useful stuff.

**Comment by f-f** [comment]
Now that #271 is in, you can use Spago to refer to the package set via a commit hash.

So if you wish to use the latest commit hash on master at the time of writing, you should use this upstream in your `packages.dhall`:

```
let upstream =
      https://github.com/purescript/package-sets/blob/81354f2ea1ac9493eb05dfbd43adc6d183bc4ecd/src/packages.dhall
```

I'll leave this open to keep track of documenting this in the README
