### ISSUE TITLE
Package set is inconsistent in github access

### ISSUE THREAD

**Issue by btrepp** [purescript/package-sets#167]
Sometimes it uses git:// sometimes https://

This lead me to an odd cause in which my machine couldn't speak over git://, and psc-package install would fail with unable to connect to github, while some packages were coming perfectly fine from github.

Can be worked around using insteadOf, but is a bit suprising!

**Comment by justinwoo** [comment]
This should be addressed now that the urls have been verified. Please let me know if there are any that do not use https://.
