### ISSUE TITLE
How about a branch for 0.11?

### ISSUE THREAD

**Issue by AlexMouton** [purescript/package-sets#174]
I am trying to get lined up with package sets, and I'm coming across many packages that are not yet included, but dont want to bring them into packages and 0.12 in one go.

**Comment by doctau** [comment]
I've got a few additional packages I want to add upstream too, but can't because there isn't a branch for 0.11.

**Comment by justinwoo** [comment]
The previous 0.11 releases have had fairly complete sets to build on, so those who want to use it should fork the package set from those tags and work with them. I wrote about how to do it before here: https://qiita.com/kimagure/items/c37b228e80318d4158f0#add-it-to-your-package-set

**Comment by justinwoo** [comment]
Sorry, I will close this for inactivity.
