### ISSUE TITLE
Add canonical package set psc-0.12.0

### ISSUE THREAD

**Issue by strax** [purescript/package-sets#182]
When running `psc-package init` with PureScript 0.12, the command will fail with

```
Initializing new project in current directory
Using the default package set for PureScript compiler version 0.12.0
(Use --source / --set to override this behavior)
warning: Could not find remote branch psc-0.12.0 to clone.
fatal: Remote branch psc-0.12.0 not found in upstream origin
```

Unless psc-package is supposed to automatically use a tag with a timestamp in the end (like `psc-0.12.0-20180524`), there should be a tag `psc-0.12.0` as well.

---
psc-package version: 0.3.2

**Comment by justinwoo** [comment]
We'll probably add this after we get `halogen` into master.

**Comment by justinwoo** [comment]
I know I said after `halogen`, but probably this will have to wait until some more "obvious" packages from contrib (like string parsers) and node get in.

**Comment by Euregan** [comment]
In the meantime, some documentation could help, particularly since the `--set` option does not seem to be usable when running `pulp --psc-package init`. Can I help with that ?

**Comment by justinwoo** [comment]
Fixed by https://github.com/purescript/package-sets/releases/tag/psc-0.12.0
