### ISSUE TITLE
Run package test suites

### ISSUE THREAD

**Issue by paf31** [purescript/package-sets#2]

**Comment by f-f** [comment]
The [alpha for the new Registry](https://discourse.purescript.org/t/registry-alpha-launched/3146) has now launched, and this entails the automation of this repository - packages in the set will be managed through [the new API](https://github.com/purescript/registry#modify-the-package-set), and a new release will be cut once a day if there are any new updates.

We have already automated the adding of new packages to the set if it compiles with it - in the future we could extend our checks to "run package tests", but in any case this should happen on the [Registry infrastructure](https://github.com/purescript/registry-dev). The pointer for this should be https://github.com/purescript/registry-dev/issues/255
