### ISSUE TITLE
Parity with Pursuit

### ISSUE THREAD

**Issue by paf31** [purescript/package-sets#21]
I doubt we'll be able to get all of these updated any time soon, but I thought it would be good to keep track of how many libraries are on Pursuit but not available in the package set.
- [x] purescript-ace
- [x] purescript-aff
- [x] purescript-aff-coroutines
- [x] purescript-ansi
- [x] purescript-argonaut
- [x] purescript-argonaut-codecs
- [x] purescript-argonaut-core
- [x] purescript-argonaut-traversals
- [x] purescript-arraybuffer-types
- [x] purescript-arrays
- [x] purescript-assert
- [x] purescript-bifunctors
- [x] purescript-canvas
- [x] purescript-catenable-lists
- [x] purescript-colors
- [x] purescript-console
- [x] purescript-const
- [x] purescript-contravariant
- [x] purescript-control
- [x] purescript-coroutines
- [x] purescript-datetime
- [x] purescript-day
- [x] purescript-distributions
- [x] purescript-distributive
- [x] purescript-dom
- [x] purescript-eff
- [x] purescript-either
- [x] purescript-enums
- [x] purescript-exceptions
- [x] purescript-exists
- [x] purescript-foldable-traversable
- [x] purescript-folds
- [x] purescript-foreign
- [x] purescript-foreign-generic
- [x] purescript-foreign-lens
- [x] purescript-form-urlencoded
- [x] purescript-free
- [x] purescript-freet
- [x] purescript-functions
- [x] purescript-functors
- [x] purescript-generics
- [x] purescript-generics-rep
- [x] purescript-globals
- [x] purescript-graphs
- [x] purescript-hoist
- [x] purescript-identity
- [x] purescript-inject
- [x] purescript-integers
- [x] purescript-invariant
- [x] purescript-isomorphisms
- [x] purescript-jquery
- [x] purescript-js-date
- [x] purescript-lazy
- [x] purescript-leibniz
- [x] purescript-lens-simple
- [x] purescript-lists
- [x] purescript-machines
- [x] purescript-maps
- [x] purescript-math
- [x] purescript-maybe
- [x] purescript-memoize
- [x] purescript-monoid
- [x] purescript-newtype
- [x] purescript-node-buffer
- [x] purescript-node-child-process
- [x] purescript-node-fs
- [x] purescript-node-fs-aff
- [x] purescript-node-http
- [x] purescript-node-path
- [x] purescript-node-process
- [x] purescript-node-readline
- [x] purescript-node-streams
- [x] purescript-node-url
- [x] purescript-nonempty
- [x] purescript-now
- [x] purescript-nullable
- [x] purescript-options
- [x] purescript-orders
- [x] purescript-pairing
- [x] purescript-parallel
- [x] purescript-parsing
- [x] purescript-partial
- [x] purescript-posix-types
- [x] purescript-pprint
- [x] purescript-preface
- [x] purescript-prelude
- [x] purescript-profunctor
- [x] purescript-profunctor-lenses
- [x] purescript-proxy
- [x] purescript-psci-support
- [x] purescript-quickcheck
- [x] purescript-quickcheck-laws
- [x] purescript-random
- [x] purescript-rationals
- [x] purescript-react
- [x] purescript-reflection
- [x] purescript-refs
- [x] purescript-rx
- [x] purescript-safely
- [x] purescript-semirings
- [x] purescript-sets
- [x] purescript-st
- [x] purescript-stalling-coroutines
- [x] purescript-strings
- [x] purescript-symbols
- [x] purescript-tailrec
- [x] purescript-taylor
- [x] purescript-thermite
- [x] purescript-these
- [x] purescript-transformers
- [x] purescript-tropical
- [x] purescript-tuples
- [x] purescript-type-equality
- [x] purescript-unfoldable
- [x] purescript-unsafe-coerce
- [x] purescript-validation
- [x] purescript-yargs
- [ ] purescript-ace-halogen
- [ ] purescript-ad-hoc
- [ ] purescript-aff-promise
- [ ] purescript-aff-reattempt
- [ ] purescript-affjax
- [ ] purescript-argonaut-generic-codecs
- [ ] purescript-arraybuffer
- [ ] purescript-b64
- [ ] purescript-behaviors
- [ ] purescript-bench
- [ ] purescript-bigints
- [ ] purescript-bound
- [ ] purescript-carpenter
- [ ] purescript-case-insensitive
- [ ] purescript-coercible
- [ ] purescript-compact
- [ ] purescript-cookies
- [ ] purescript-cowlaser
- [ ] purescript-cowlaser-http
- [ ] purescript-cowlaser-node
- [ ] purescript-css
- [ ] purescript-csv
- [ ] purescript-cycle-run
- [ ] purescript-d3
- [ ] purescript-debugger
- [ ] purescript-easyimage
- [ ] purescript-echarts
- [ ] purescript-eff-functions
- [ ] purescript-ejson
- [ ] purescript-encoding
- [ ] purescript-equatable-functions
- [ ] purescript-errors
- [ ] purescript-eulalie
- [ ] purescript-eval
- [ ] purescript-exists-eq
- [ ] purescript-exitcodes
- [ ] purescript-express
- [ ] purescript-fedger
- [ ] purescript-filterable
- [ ] purescript-fixed-points
- [ ] purescript-flare
- [ ] purescript-flarecheck
- [ ] purescript-flaredoc
- [ ] purescript-format
- [ ] purescript-free-canvas
- [ ] purescript-gametree
- [ ] purescript-halogen
- [ ] purescript-halogen-bootstrap
- [ ] purescript-halogen-css
- [ ] purescript-halogen-echarts
- [ ] purescript-halogen-menu
- [ ] purescript-hash
- [ ] purescript-homogeneous-objects
- [ ] purescript-howler
- [ ] purescript-http-methods
- [ ] purescript-hugenums
- [ ] purescript-imagediff
- [ ] purescript-int-53
- [ ] purescript-isometric
- [ ] purescript-isotypes
- [ ] purescript-jack
- [ ] purescript-js-timers
- [ ] purescript-jtable
- [ ] purescript-jwt
- [ ] purescript-kanren
- [ ] purescript-localstorage
- [ ] purescript-logging
- [ ] purescript-markdown-halogen
- [ ] purescript-matrices
- [ ] purescript-matrix
- [ ] purescript-media-types
- [ ] purescript-mkdirp
- [ ] purescript-neo4j
- [ ] purescript-node-os
- [ ] purescript-node-postgres
- [ ] purescript-node-telegram-bot-api
- [ ] purescript-numbers
- [ ] purescript-observable
- [ ] purescript-observable-channel
- [ ] purescript-observable-lift
- [ ] purescript-observable-time
- [ ] purescript-ogmarkup
- [ ] purescript-pairs
- [ ] purescript-phantom
- [ ] purescript-phoenix
- [ ] purescript-pouchdb
- [ ] purescript-pouchdb-ffi
- [ ] purescript-pux-document-title
- [ ] purescript-pux-spectacle
- [ ] purescript-pux-spectacle-codeslide
- [ ] purescript-quantities
- [ ] purescript-ractive
- [ ] purescript-redux
- [ ] purescript-remotecallback
- [ ] purescript-routing
- [ ] purescript-rx-state
- [ ] purescript-search
- [ ] purescript-servant-support
- [ ] purescript-sexp
- [ ] purescript-signal
- [ ] purescript-signal-loop
- [ ] purescript-signal-socket
- [ ] purescript-simple-parser
- [ ] purescript-simple-repl
- [ ] purescript-simple-request
- [ ] purescript-slides
- [ ] purescript-smolder
- [ ] purescript-smolder-vdom
- [ ] purescript-spec
- [ ] purescript-spec-mocha
- [ ] purescript-sqlite
- [ ] purescript-stringutils
- [ ] purescript-subscriber
- [ ] purescript-template-strings
- [ ] purescript-test-unit
- [ ] purescript-transformerless
- [ ] purescript-treemap
- [ ] purescript-typedarray
- [ ] purescript-typelevel
- [ ] purescript-uint
- [ ] purescript-uuid
- [ ] purescript-vdom
- [ ] purescript-vector
- [ ] purescript-verbal-expressions
- [ ] purescript-web-storage
- [ ] purescript-webgl
- [ ] purescript-webidl
- [ ] purescript-websocket-simple
- [ ] purescript-webworkers
- [ ] purescript-xstream
- [ ] purescript-yarn
- [ ] purescript-zclipboard

**Comment by Pauan** [comment]
After looking through the `bower_components` of my app, the only package which is missing from `package-sets` is `purescript-test-unit`

I'd really appreciate it if it could be added, though that may depend on @bodil
