### ISSUE TITLE
Guidelines?

### ISSUE THREAD

**Issue by ad-si** [purescript/package-sets#228]
Are there any guidelines which packages should / will be included?
In other words: If I open a merge request for a few random packages, will they be merged? 😛

**Comment by JordanMartinez** [comment]
I'm also curious about this because there are some package that work for `0.12.0` but aren't currently in the default package set.

**Comment by justinwoo** [comment]
In general yes, even random packages will be merged. I have been making pull requests to the libraries upstream personally, and I will start to drop packages more quickly as upstreams do not show signs of activity.
