### ISSUE TITLE
RFC: unification with Spacchetti

### ISSUE THREAD

**Issue by f-f** [purescript/package-sets#270]
With the release of [spago](https://github.com/spacchetti/spago) some time ago, we now have another PureScript package manager based on package-sets.

However, Spago cannot use this package-set as Psc-package does (the reason is that its package-set has to be a Dhall file), so we maintain the [spacchetti package-set](https://github.com/spacchetti/spacchetti), and this is additional work for us maintainers and possibly confusing for users.

At this point in time the goal of the Spacchetti experiment (TL:DR: validate that Dhall saves some amount of headaches both when managing and when using a package-set, see [here](https://github.com/spacchetti/spacchetti#the-raisin-deets)) has been reached in my opinion, and I don't see much point in maintaining a separate Spacchetti repo anymore.

So I'd like to propose the *unification of Spacchetti into this repo*, since:
- the two repos are both maintained by @justinwoo 
- they contain basically the same packages anyways (e.g. [see this script](https://github.com/purescript/package-sets/blob/master/UPDATE))
- having this package-sets separation is confusing for users and not good for UX in general (e.g. last related Spago issue: https://github.com/spacchetti/spago/issues/118)

This unification would entail that:
- the Dhall source from Spacchetti would move here
- the `packages.json` would be generated from the Dhall source, and both would be checked in CI (as it happens currently in Spacchetti's CI)
- the Spacchetti repo would be deprecated in favor of this one
  - which would then become Spago's default package-set
- we'd concentrate maintainership effort: @justinwoo would have to maintain only one package-set instead of two and I'd help maintaining this one

**Comment by justinwoo** [comment]
Done with no objections from any
