### ISSUE TITLE
Conflicting module names

### ISSUE THREAD

**Issue by klntsky** [purescript/package-sets#451]
`text-encoding` by @AlexaDeWit and `encoding` by @menelaos both define `Data.TextDecoder` and `Data.TextEncoder` modules. This prevents me from compiling all packages in the set.

https://github.com/AlexaDeWit/purescript-text-encoding
https://github.com/menelaos/purescript-encoding

**Comment by f-f** [comment]
Oh, I wonder how come CI allowed this to happen 🤔

**Comment by klntsky** [comment]
Where's the CI code?

**Comment by justinwoo** [comment]
This sounds pretty normal. We don't acme build all of the packages together, but only as units of individual packages. If you want to acme it, you will have to make it happen in CI.

**Comment by AlexaDeWit** [comment]
Sorry for the conflict folks. The reason for the name conflict is kind of intentional. @menelaos had been busy and away for a while, and so after a while of radio silence, I released a fork of the repo. Mine contains a bit of work not found in the other.

Just a bit of a background. Mine is meant to be a drop-in replacement.

**Comment by f-f** [comment]
@AlexaDeWit no worries at all! 
Though I think we should forbid duplicated module names in the set in order to be able to generate docs (for which we need to build the whole set together, see #6)

**Comment by klntsky** [comment]
I [blacklisted](https://github.com/spacchetti/starsuit/blob/cb98af537804a2b8ea5918337ed3f0ecfdca8a9c/index.js#L11) failing packages for now. However, if there were other packages depending on  `text-encoding`, they'd have to be blacklisted too.

I agree with @f-f that forbidding duplicated module names is good, because otherwise users may face unwanted surprises because of conflicting transitive dependencies.

**Comment by menelaos** [comment]
Just wanted to confirm that [`purescript-encoding`](https://github.com/menelaos/purescript-encoding) is still maintained, mainly for [`purescript-b64`](https://github.com/menelaos/purescript-b64). 

@AlexaDeWit From a quick look, it seems that the only user-facing difference is in the added [error message](https://github.com/AlexaDeWit/purescript-text-encoding/commit/46ef20a21a0d7f2fa560de818f04391ab5db27d3), right?

This issue of drop-in replacements is probably related to https://github.com/purescript/purescript/issues/2437.

**Comment by AlexaDeWit** [comment]
Correct, that's the only change that's been brought in. The fork originated a while ago.

I think that I will, when I resume work on my open source stuff in a couple months, migrate my package naming away, and move it into a fully fledged fork.

Unfortunately at this time, my fork also has things built on top of it. But it seems none of my other projects are in this package-set anyway, so it might be the simplest situation to simply remove mine, favoring menalaos instead for that namespace, given that mine will move later this year?

**Comment by menelaos** [comment]
Since there seems to be a (slow) [trend](https://github.com/purescript/purescript-effect/issues/1) to move away from `Control.` and `Data.` namespaces, I'd like to eventually rename `Data.TextDecoder` to `Encoding.TextDecoder` or simply `TextDecoder`. I was planning on waiting for a few more core packages to make that transition, though.

**Comment by f-f** [comment]
@menelaos @AlexaDeWit it seems we didn't end up with a clear plan here, so: should we go for dropping `text-encoding` for now or should we wait for a version of either `encoding` or `text-encoding` with the new namespaces?

**Comment by AlexaDeWit** [comment]
I suggest dropping mine for now.
