### ISSUE TITLE
Affjax should be removed from the current set

### ISSUE THREAD

**Issue by garyb** [purescript/package-sets#467]
It's not compatible with `form-urlencoded` v5 and hasn't been updated yet.

**Comment by justinwoo** [comment]
thanks

**Comment by vlatkoB** [comment]
Seems it is updated and merged to `v9.0.1`. 
https://github.com/slamdata/purescript-affjax/issues/139
https://github.com/slamdata/purescript-affjax/pull/140

**Comment by garyb** [comment]
It's not up to date yet, it needs some breaking changes: https://github.com/slamdata/purescript-affjax/issues/141
