### ISSUE TITLE
missing .git for unsafe-reference seems to make it unusable from spago

### ISSUE THREAD

**Issue by bjornkihlberg** [purescript/package-sets#499]
The [unsafe-reference](https://github.com/purescript-contrib/purescript-unsafe-reference) package doesn't seem to work with [spago](https://github.com/spacchetti/spago) because the repo link is missing a **.git** at the end.
```json
  "unsafe-reference": {
    "dependencies": [],
    "repo": "https://github.com/purescript-contrib/purescript-unsafe-reference",
    "version": "v3.0.1"
  },
```

**Comment by justinwoo** [comment]
Fixed in #502
