### ISSUE TITLE
0.10.7 package set?

### ISSUE THREAD

**Issue by pkamenarsky** [purescript/package-sets#52]
Settin the package set to 0.10.6 in `psc-package.json` using psc 0.10.7 doesn't seem to work, and there's no 0.10.7 package set yet.

    $ psc-package install psci-support
    Updating 4 packages...
    Updating console
    Updating eff
    Updating prelude
    Updating psci-support
    psc-package.json file was updated

    $ psci
    PSCi requires the psci-support package to be installed.

**Comment by paf31** [comment]
I'll make a tag, but note that you still need to pass input files to `psci`.
