### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by thought2** [purescript/package-sets#560]
Includes:

https://github.com/purescript/package-sets/pull/558
https://github.com/purescript/package-sets/pull/559

**Comment by justinwoo** [comment]
Sure, we can make one

**Comment by justinwoo** [comment]
https://github.com/purescript/package-sets/releases/tag/psc-0.13.6-20200127

Give Travis like 20 min to finally run and upload the normalized packages.dhall on the release

**Comment by thought2** [comment]
Nice, thanks!
