### ISSUE TITLE
Help to add purescript-web-socket package

### ISSUE THREAD

**Issue by flip111** [purescript/package-sets#581]
I would like to add `purescript-web-socket`. It is on [bower](https://bower.io/search/). When i read the contributing guide it talks about a `pulp` version, i have no idea what to do with that or what version to give. It's not my package. Can i do anything to add it to the package set?

**Comment by f-f** [comment]
Hi @flip111! If the package is on Bower then it should be enough to add the package information to the relevant Dhall file and then run `make` - e.g. see #569 for an example of how to do that

**Comment by flip111** [comment]
I tried `spago install websocket` and then looked in the json file and still could not found it. Now that i wanted to edit this file i finally saw it's called `web-socket` with a dash. So i will close this issue for now, but i will remember the information in case i want to add another package. Thanks for the help !

**Comment by f-f** [comment]
You're welcome 😊
