### ISSUE TITLE
requirements for adding a package

### ISSUE THREAD

**Issue by flip111** [purescript/package-sets#584]
Was thinking to make a pull request on a slight modification of https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md

Just that i don't know exactly where to put this.

The following programs are required

* dhall (package: dhall)
* dhall-to-json (package: dhall-json)
* psc-package -- maybe mentioned somewhere

**Comment by f-f** [comment]
These requirements are [listed, but quite far into the file](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#prerequisites), maybe we could move them a bit before?

Also there's the issue that the versions don't always match the latest, so maybe it would be useful to list the exact versions?

**Comment by flip111** [comment]
Yes please if would be great if this

https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#prerequisites

comes before this

https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#how-to-add-a-package-to-the-set

I guess you can list the exact versions, but installing specific versions of tools is not always so easy.

**Comment by f-f** [comment]
@flip111 if you want to open a PR for this that would be great, otherwise I'll get back to this in a bit

I guess a good path would also be to ask people to run `nix-shell --command make` instead of trying to install the packages locally. Though this wouldn't work with Windows.
