### ISSUE TITLE
nix-shell --command make   not updating packages.json with new dhall file

### ISSUE THREAD

**Issue by flip111** [purescript/package-sets#597]
I created a new dhall file locally `flip111.dhall`, when i run `nix-shell --command make` `packages.json` is not updated.

By the way ... i also get that it changes reindent on all other dhall files ... I don't know why this keeps happening

**Comment by f-f** [comment]
@flip111 you have to add the new file to the groups, e.g. see #594 

As for the nix-shell, it works as intended on my machine, so maybe the environment is leaking in your case. Could you run `dhall --version` inside the nix shell?

**Comment by flip111** [comment]
I got it packages.json updated, so that's one thing :)

For dhall version i have `1.31.1`

**Comment by f-f** [comment]
That should be the right version. As far as I can tell the `nix-shell` from this repo works as intended on all my machines, can someone else try to replicate?

**Comment by flip111** [comment]
I noticed that it went from 4 spaces indent to 2 spaces indent and in the repository it's also on 2 spaces indent. So it goes towards the amount of indent what already is. Part of my git diff:

```
diff --git a/src/groups/ad-si.dhall b/src/groups/ad-si.dhall
index 14ec6b6..23f4c3c 100644
--- a/src/groups/ad-si.dhall
+++ b/src/groups/ad-si.dhall
@@ -1,6 +1,6 @@
 { result =
-    { dependencies = [ "either", "foldable-traversable", "prelude" ]
-    , repo = "https://github.com/ad-si/purescript-result.git"
-    , version = "v1.0.3"
-    }
+  { dependencies = [ "either", "foldable-traversable", "prelude" ]
+  , repo = "https://github.com/ad-si/purescript-result.git"
+  , version = "v1.0.3"
+  }
 }
```

So i was pretty sure i based my patch on master. Looking in `git log -2`

```
commit ab14f611228039916c730b6d9c8be8add68bb7d9 (HEAD -> patch-6, origin/patch-6)
Author: flip111 <fip101@gmail.com>
Date:   Mon Apr 6 19:39:23 2020 +0200

    Add ordered-set

commit e689c7da77b3b0589eb8afd52d905099dd09dfad (upstream/master, origin/master, origin/HEAD, master)
Author: SpacchettiBotti <45738712+spacchettibotti@users.noreply.github.com>
Date:   Mon Apr 6 19:27:17 2020 +0200

    Updates 2020-04-05 (#595)
    
    * Updates 2020-04-05
    
    * Updates 2020-04-05
    
    Co-authored-by: Fabrizio Ferrai <fabrizio.ferrai@gmail.com>
    Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
```

https://github.com/purescript/package-sets/blob/master/src/groups/ad-si.dhall

I don't understand this situation. Maybe i can fetch from upstream to update master and then start over on a new branch?

**Comment by f-f** [comment]
Yeah it should be enough to do a `git pull origin master --rebase`, but also starting over if that doesn't work sounds like a good idea

**Comment by flip111** [comment]
Original problem what this issue was about is been fixed with this comment https://github.com/purescript/package-sets/issues/597#issuecomment-612839684

Additional indent problem is also fixed with a new clone / rebase upstream / branch

Thanks for support

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:
