### ISSUE TITLE
Package-set version shield

### ISSUE THREAD

**Issue by athanclark** [purescript/package-sets#605]
It would be a nice aesthetic for packages to showcase what their latest package-set version is compliant with, similar to how pursuit generates badges for the latest version they host.

Something pretty like this would be nice: ![](https://img.shields.io/badge/package--set-v0.13.5-blueviolet)

I'm not sure if this issue would belong here, or should be handled by pursuit itself though.

**Comment by f-f** [comment]
The [alpha for the new Registry](https://discourse.purescript.org/t/registry-alpha-launched/3146) has now launched, and this entails the automation of this repository - packages in the set will be managed through [the new API](https://github.com/purescript/registry#modify-the-package-set), and a new release will be cut once a day if there are any new updates.

So no human is expected to be manually modifying this repo anymore, and we are not planning for this to be the main reference we point folks to - this info will likely be taken care in a new frontend built on top of the registry.
