### ISSUE TITLE
Managing argonaut-codecs update

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/package-sets#642]
The `argonaut-codecs` package has been updated to `v7.0.0`, which introduces typed errors. A number of libraries in the ecosystem depend either on `argonaut` or `argonaut-codecs`, which I have listed below.

All of the libraries below have links to their open pull requests which update them, or if they've already been updated, the links point to their release which includes the change.

I'd like to avoid updating argonaut-codecs and these libraries until most or all of them have had the chance to update so that we can have a graceful move from one package set to the next. But if that's not a reasonable ask, then I'm open to taking another approach.

I don't know if a change has propagated through a lot of libraries in the package set before, so I'm not sure if I'm handling this in the best way. Maybe this can be a nice warmup for all the changes that will happen with PureScript 0.14!

I'm open to advice on how to make sure this is an effective transition.

- [x] [purescript-contrib/argonaut](https://github.com/purescript-contrib/purescript-argonaut/releases/tag/v7.0.0)
- [x] [purescript-contrib/argonaut-generic](https://github.com/purescript-contrib/purescript-argonaut-generic/releases/tag/v6.0.0)
- [x] [purescript-contrib/argonaut-traversals](https://github.com/purescript-contrib/purescript-argonaut-traversals/releases/tag/v8.0.0)
- [x] [matthew-hilty/struct](https://github.com/matthew-hilty/purescript-struct/pull/2) (PR still open, but library is compatible with both Argonaut versions)
- [x] [matthew-hilty/tolerant-argonaut](https://github.com/matthew-hilty/purescript-tolerant-argonaut/releases/tag/v2.0.0)
- [x] [flip111/ordered-set](https://github.com/flip111/purescript-ordered-set/pull/1)
- [ ] [joneshf/option](https://github.com/joneshf/purescript-option/pull/22)
- [x] [thomashoneyman/slug](https://github.com/thomashoneyman/purescript-slug/releases/tag/v2.0.0)
- [x] [purescript-hyper/hyper](https://github.com/purescript-hyper/hyper/releases/tag/v0.11.1)
- [x] [purescript-hyper/purescript-trout](https://github.com/purescript-hyper/purescript-trout/releases/tag/v0.12.3)
- [x] [purescript-hyper/purescript-trout-client](https://github.com/purescript-hyper/purescript-trout-client/releases/tag/v0.12.1)
- [x] [purescript-hyper/purescript-hypertrout](https://github.com/purescript-hyper/purescript-hypertrout/pull/20)
- [x] [drewolson/biscotti-session](https://github.com/drewolson/purescript-biscotti-session/releases/tag/v0.1.2)
- [x] [drewolson/httpure-contrib-biscotti](https://github.com/drewolson/purescript-httpure-contrib-biscotti/releases/tag/v0.1.2)
- [x] [natefaubion/psa-utils](https://github.com/natefaubion/purescript-psa-utils/releases/tag/v7.0.0)
- [x] [athanclark/uint-instances](https://github.com/athanclark/purescript-uint-instances/releases/tag/v0.0.2)
- [x] [athanclark/websocket-moderate](https://github.com/athanclark/purescript-websocket-moderate/releases/tag/v7.0.2)
- [x] [kritzcreek/psc-ide](https://github.com/kritzcreek/purescript-psc-ide/releases/tag/v16.0.0)
- [x] [klntsky/bower-json](https://github.com/klntsky/purescript-bower-json/releases/tag/v2.0.0)
- [x] [bodil/sized-vectors](https://github.com/bodil/purescript-sized-vectors/releases/tag/v5.0.1)
- [x] [danieljharvey/refined](https://github.com/danieljharvey/purescript-refined/releases/tag/v1.0.0)
- [ ] [paluh/polyform-validators](https://github.com/paluh/purescript-polyform-validators/pull/1)
- [x] [cprussin/monad-logger](https://github.com/cprussin/purescript-monad-logger/pull/6)

**Comment by f-f** [comment]
Thanks for doing this! I think we are fine waiting for the propagation. Let's see how this evolves and where we are in a week or so

**Comment by seanyu4296** [comment]
Adding to the list
[](https://github.com/jmackie/purescript-datetime-iso) jmackie/purescript-datetime-iso

**Comment by f-f** [comment]
@seanyu4296 it doesn't seem like `datetime-iso` depends on `argonauts-codec`?

**Comment by f-f** [comment]
@seanyu4296 it doesn't seem like `datetime-iso` is in the current package set though?

**Comment by thomashoneyman** [comment]
Only 3 libraries remain without updates, and in each case the author / maintainers have not responded since I opened the original pull requests 13 days ago, or to my followups since then. Should we wait 1 more week and then merge #651?

**Comment by seanyu4296** [comment]
Oh okay I'll remove it I thought the list should include all the libraries in the wild that depended on argonaut codes @f-f

**Comment by f-f** [comment]
@thomashoneyman usually I'd say two weeks is plenty of time to merge a PR, but on the other hand it's July and lots of people are on vacation, so even waiting a month might be fine?

And while we're talking about this: we should really update [our documentation about when packages will be dropped](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#will-any-package-be-dropped-at-any-point). I don't have strong opinions on this, but in there we give maintainers 'one week' after they are notified to update their package - given our experience here I feel this might be a little bit of a short notice? :thinking:

**Comment by thomashoneyman** [comment]
A week does feel short — the maintainer could have a busy week at work, or be on vacation, or whatever else, and I at least would feel rushed if it was “Merge this in the next couple days or be dropped from the set.”

Two weeks seems more reasonable, and a month feels too long except for perhaps fundamental libraries like Aff. Maybe language that says “At minimum two weeks notice”?

That said, on a case by case basis I think it’s ok to push that deadline back if the upgrade is non-urgent like this one, vs. something more pressing like a compiler release.

**Comment by thomashoneyman** [comment]
Closed by #651
