### ISSUE TITLE
What's the point of releases without a date?

### ISSUE THREAD

**Issue by f-f** [purescript/package-sets#647]
I am not sure why we're publishing releases that don't have a date attached, but only the compiler version (e.g. `psc-0.13.8`), are they needed for something?

cc @justinwoo

**Comment by justinwoo** [comment]
https://github.com/purescript/psc-package/blob/24a696131bca63513a84d0a9b691f773c7b37069/app/Main.hs#L340

**Comment by f-f** [comment]
Cool, thanks. We should update the [docs about release naming then](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#releases).
Also the new CI (with GitHub actions) requires that only the tag gets created, so that CI will create the release. We could enforce/automate all of this in the makefile

**Comment by f-f** [comment]
The [alpha for the new Registry](https://discourse.purescript.org/t/registry-alpha-launched/3146) has now launched, and this entails the automation of this repository - packages in the set will be managed through [the new API](https://github.com/purescript/registry#modify-the-package-set), and a new release will be cut once a day if there are any new updates.

So no human is expected to be manually modifying this repo anymore, and the logic for how these releases are called now lives [in the `registry-dev` repo.](https://github.com/purescript/registry-dev/blob/51da4ad62adfc627ebef501e9873571849cce895/src/Registry/Legacy/PackageSet.purs#L281)
