### ISSUE TITLE
Version Check: 1 package(s) ⚠️

### ISSUE THREAD

**Issue by andys8** [purescript/package-sets#728]
# Packages

1 package(s) ⚠️

* arraybuffer-builder (jamesdbrock/purescript-arraybuffer-builder) v2.1.0 -> v3.0.1 ✖

# About this Issue

This issue is **updated automatically**. It can be closed and will be re-opened in case there are new updates available.

See <https://github.com/purescript/package-sets/tree/master/ci>

**Comment by JordanMartinez** [comment]
Nice!

**Comment by thomashoneyman** [comment]
These automated updates are no longer necessary since the registry releases daily package sets.
