### ISSUE TITLE
purescript-numbers?

### ISSUE THREAD

**Issue by LATBauerdick** [purescript/package-sets#74]
I may be missing something fundamental, but I have difficulty using pcs-package to build my program because purescript-numbers seems to be missing from the package set for 0.11.4

I need fromString :: String -> Maybe Number, and I assume others would too (there are fromString implementations for Int, Decimals etc provided, but not for Numbers!)

I don't quite know yet how to produce a pull request to fix this, so forgive me if I'm just creating an issue instead. 

Best regards, LatB

**Comment by thoradam** [comment]
PR up #75.
