### ISSUE TITLE
request: purescript-observable

### ISSUE THREAD

**Issue by waynevanson** [purescript/package-sets#742]
https://github.com/bodil/purescript-observable

If there are any other multi-push based ways of handling data in purescript, I'd love to know.

I'd be satisfied with RXJS or the mentioned implementation.

I've tried to convert the package myself but I struggle to navigate the language.

**Comment by f-f** [comment]
As maintainers we don't strive to add packages to the set ourselves: our job is to keep the set compiling with the latest upstream versions of packages, so we upgrade all the existing ones, and eventually drop packages that don't keep up with the ecosystem moving forward.
In this light you might notice that by adding packages ourselves we'd only make our maintainership burden higher.

So, you won't see us adding packages nor we take such requests - however pull requests to add packages are most welcome and will be merged as long as CI continues to build!
So I'll close this issue, but you might want to ask [on Discourse](https://discourse.purescript.org/) for help with adding the package to the set :slightly_smiling_face:
