### ISSUE TITLE
graphql-client naming collision

### ISSUE THREAD

**Issue by toastal** [purescript/package-sets#805]
There are two libraries with name `graphql-client`

as of 2021-02-03:

**Project A:** https://github.com/purescript-graphql-client/purescript-graphql-client
[Unmerged to package-sets](https://github.com/purescript-graphql-client/purescript-graphql-client/issues/23), [announced on Discourse (2020-07-20)](https://discourse.purescript.org/t/purescript-graphql-client/1560), [published NPM package](https://www.npmjs.com/package/purescript-graphql-client), 18 stars, 6 watchers, GitHub says used by 0 projects, first commit on 2019-06-07

**Project B:** https://github.com/OxfordAbstracts/purescript-graphql-client
[Merged to package-sets (reserving the name `graphql-client`)](https://github.com/purescript/package-sets/pull/797), 2 stars, 1 watcher, GitHub says used by 3 projects, first commit on 2021-01-18

I have a bit of a bias contributing to _Project A_ and using it in production, but what I'm most concerned about is reaching some sort of consensus between names and duplicated effort in an already small language -- nor do I feel either project is entitled to the name `graphql-client` (both have tests and examples and it looks like they're doing similar things). _Project A_ is now looking for a new name because it wasn't reserved, but I'm not really sure what makes sense at this point or what the differences are between these projects. A clear names can help users choose and understand what project to use at a glance of the name (and _Project A_ not resorting to being named after an Asian snack food lol). I'm hoping maybe @srghma and @roryc89 can maybe shed light on the differences between these projects and how we can resolve a naming issue that benefits PureScript+GraphQL users' understanding (maybe both need a different, more specific name?).

Perhaps there were other discussions I missed out on, but I'm trying to understand what's going on.

**Comment by srghma** [comment]
> shed light on the differences between these projects

since https://github.com/purescript-graphql-client/purescript-graphql-client is port of https://github.com/dillonkearns/elm-graphql/

maybe rename to `https://github.com/purescript-dillonkearns-graphql-client/purescript-dillonkearns-graphql-client`?

**Comment by toastal** [comment]
Is one project doing something the other isn't? Is there a recommendation?

**Comment by srghma** [comment]
@toastal 

> Is one project doing something the other isn't?

Project A: https://github.com/purescript-graphql-client/purescript-graphql-client
vs
Project B: https://github.com/OxfordAbstracts/purescript-graphql-client

the generated schema is diff

```
type Query {
  books(first: Int, last: Int!): [Book!]!
  authors: [Author!]!
}
```

to

```
module Schema.MyModule where

import Data.Maybe (Maybe)
import Data.Newtype (class Newtype)
import GraphQL.Client.Args (class ArgGql, class RecordArg, type (==>), NotNull)

type Query = 
  { books :: 
    { first :: Int
    , last :: (NotNull Int)
    }
    ==> (Array Book)
  , authors :: (Array Author)
  }
```

also it user can use `@apollo/client` npm package, with subscriptions built in

> Is there a recommendation?

cannot tell, maybe @roryc89 can tell more

**Comment by srghma** [comment]
cannot add to package-sets because generator depends on optparse https://github.com/purescript/package-sets/issues/856

**Comment by roryc89** [comment]
Hi @toastal and @srghma, just seen this. When I created my package I didn't realise there was already a purescript graphql client available. I believe I only searched on pursuit so didn't see it. 

I don't mind renaming our project, especially if https://github.com/purescript-graphql-client/purescript-graphql-client is already being more widely used and would benefit more people. 

I haven't used  https://github.com/purescript-graphql-client/purescript-graphql-client so I'm not sure of the differences between the projects but I can briefly lay out how ours works. 

It's basically split into 2 parts. 

A typed client that wraps a lower level client (either Affjax or JS implementations, such as Apollo) and a codegen tool that generates a purescript schema from a graphql schema, which allows type checking. 

It supports queries, mutations, subscriptions, watchQueries, client caching and cache updates. 

I think that the examples in https://github.com/OxfordAbstracts/purescript-graphql-client/tree/main/examples should give a good overview of the features and syntax. The `src/Main.purs` and `server-fn.js` files are probably the most important.

I hope this helps. Please let me know there's anything else you need!

**Comment by srghma** [comment]
> I don't mind renaming our project, especially if https://github.com/purescript-graphql-client/purescript-graphql-client is already being more widely used and would benefit more people

@roryc89 you are very kind, tnx, but we have already renamed org and package to https://github.com/purescript-graphqlclient/purescript-graphqlclient, waiting for optparse to be readded to package-sets and will make a pr

**Comment by roryc89** [comment]
@srghma ok glad to hear it's all sorted in the end :)

**Comment by roryc89** [comment]
If this confuses users, I can add a section to our README outlining the differences between the 2 projects

**Comment by srghma** [comment]
@roryc89 yes, please

**Comment by roryc89** [comment]
No problem. But I don't know what the differences are yet, other than those you outlined in https://github.com/purescript/package-sets/issues/805#issuecomment-773254869

**Comment by f-f** [comment]
It looks like this has been resolved. Thank you all for this! I'll close this then :slightly_smiling_face:
