### ISSUE TITLE
Latest tag for 0.14 set wasn't created

### ISSUE THREAD

**Issue by darichey** [purescript/package-sets#870]
latest-compatible-sets.json has `psc-0.14.0-20210316` as the 0.14 tag, but this tag does not exist. It seems like the release workflow [didn't run](https://github.com/purescript/package-sets/actions/workflows/release.yml).

**Comment by f-f** [comment]
[Fixed](https://github.com/purescript/package-sets/releases/tag/psc-0.14.0-20210317)
