### ISSUE TITLE
server-sent-events missing?

### ISSUE THREAD

**Issue by goertzenator** [purescript/package-sets#913]
I've updated a spago project to purescript-0.14 and new packageset, but a dependent package `server-sent-event` appears to be missing.

I see it in the sources:
https://github.com/purescript/package-sets/blob/psc-0.14.0-20210406/src/groups/michaelxavier.dhall

But I do not see it in the distributed package set:
https://github.com/purescript/package-sets/releases/download/psc-0.14.0-20210406/packages.dhall

For reference, the last package set I was using does indeed have it: https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20200822/packages.dhall

What happened to `server-sent-events`?

**Comment by JordanMartinez** [comment]
It actually isn't apart of the package sets we've released yet. If you look at the `michaelxavier.dhall` file, you'll see that [the package is still commented out](https://github.com/purescript/package-sets/blob/master/src/groups/michaelxavier.dhall#L1-L8). The library either doesn't compiler on PureScript `v0.14.0` yet or has dependencies that don't.

**Comment by thomashoneyman** [comment]
I took a quick look at the dependencies and it looks like they do compile on PureScript 0.14. The package might still compile with PureScript 0.14, but if it doesn't then the author would need to update it and then submit a PR to package-sets to uncomment that package.

**Comment by goertzenator** [comment]
[forehead slap] I totally didn't notice it was commented out, thanks.  I'll see if I can get that package updated.
