### ISSUE TITLE
Should there be mirrors?

### ISSUE THREAD

**Issue by toastal** [purescript/package-sets#937]
Like all servers, there are times when GitHub is down and not everyone uses GitHub so it's uptime becomes everyone's problem. I think even one backup mirror could be handy to everyone. One easy, low-hanging option could be automatic pull [mirroring on GitLab](https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html) and a [generic package repository](https://docs.gitlab.com/ee/user/packages/generic_packages/index.html) for build outputs. But even SourceHut or self-hosted git repo could be good too. With an automatic mirror Dhall can do Dhall things and fallback to a the mirror if one server is down and still verifying the hash ala

```dhall
let version : Text = "psc-0.14.1-20210506"
let upstream =
      https://github.com/purescript/package-sets/releases/download/${version}/packages.dhall sha256:d199e142515f9cc15838d8e6d724a98cd0ca776ceb426b7b36e841311643e3ef
    ? https://gitlab.com/purescript/package-sets/somedir/${version}/packages.dhall sha256:d199e142515f9cc15838d8e6d724a98cd0ca776ceb426b7b36e841311643e3ef

in upstream
```

This could be built into Spago as well so users don't have to think about it. There is nothing preventing anyone from doing this now, but maybe official instead of unofficial package-set mirror would be preferred?

- - -

Most (if not all) current libraries are hosted under GitHub, but there's no technical reason that would have to be the case. I feel ideally even the packages could have a `Package ⩓ { mirrors : List Repo }` option for more resilience. In the past using Elm, the entire community grinds to a massive halt and builds fail because of a GitHub outage since the whole package system is built on key-value pair of GitHub username+GitHub project name lock-in.

**Comment by thomashoneyman** [comment]
With the new registry, packages will be available via our own storage backend as well as via GitHub; I don’t see any reason not to host package sets ourselves as well as on GitHub. I’m not sure if we already have plans for this, but it’s a good idea!

**Comment by f-f** [comment]
@toastal as @thomashoneyman already introduced, we already considered this issue when designing the new registry. You can read more about it [here](https://github.com/purescript/registry#mirroring-the-registry).

In short:
- the registry itself is just a bunch of CI running on Actions, and can easily be run elsewhere
- its metadata is just a git repo, can be mirrored
- the packages won't come from GitHub, but are stored (by our CI) at the time of publishing, in a "storage backend". This means that they won't go down with GitHub. We also have buitin support for adding more storage backends - we'll start with at least one, maintained by the packaging team
