### ISSUE TITLE
Dropped packages

### ISSUE THREAD

**Issue by lukasturcani** [purescript/package-sets#945]
I've noticed that my packages were dropped from the package set in this PR (https://github.com/purescript/package-sets/pull/816) based on the docs here (https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#will-any-package-be-dropped-at-any-point) I assumed that I would get an issue filed in my repos if they were in danger of getting dropped because of some kind of incompatibility, I don't think I ended up getting one of those. I've looked at the commit and PR, which dropped the packages (#816 ) and didn't find any info on why the packages were dropped. Is it alright if I try to add them back?

**Comment by thomashoneyman** [comment]
Hi @lukasturcani! We dropped all packages that did not compile with PureScript 0.14 and the updated core libraries for PureScript 0.14. If your packages are compiling with the set then they are absolutely welcome!

Ordinarily we notify folks if their packages have incompatibilities, but for a compiler transition that process simply doesn't scale. When a new compiler release comes out we ensure that all core libraries are included in the initial package set, plus any packages that still compile, and everything else is commented out and re-added as authors are able to update their packages.

**Comment by lukasturcani** [comment]
Many thanks for the response, that's perfectly understandable. I will update the packages to work with the new compiler and try to add them back.
