### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by toastal** [purescript/package-sets#989]
I'm sure we already know [EditorConfig](https://editorconfig.org/). Halogen has [one](https://github.com/purescript-halogen/purescript-halogen/blob/master/.editorconfig) as do many other projects and it would help with consistency. My editor was giving me 8-spaced tabs (default in Vims) without having this file.

**Comment by thomashoneyman** [comment]
If you'd like to add an EditorConfig file similar to the one used in the PureScript Contributors organization I'm happy to merge it. Thanks!

**Comment by f-f** [comment]
The [alpha for the new Registry](https://discourse.purescript.org/t/registry-alpha-launched/3146) has now launched, and this entails the automation of this repository - packages in the set will be managed through [the new API](https://github.com/purescript/registry#modify-the-package-set), and a new release will be cut once a day if there are any new updates.

So no human is expected to be manually modifying this repo anymore, and we can consider this issue solved.
