### ISSUE TITLE
Add a RELEASE_GUIDE.md file

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/package-sets#995]
Ideally, [this line I'm proposing we add in the purescript RELEASE_GUIDE.md file](https://github.com/purescript/purescript/pull/4177/files#diff-3dd37fe82be5315d56d3db6442ffe1e6993df584f98cc13d3aff2f02a027843eR138) would link to a file here that explains to maintainers how to make a release.

Documenting this means more people could make a release in case someone is away on vacation.

**Comment by cdepillabout** [comment]
Reading through the `spago` source code, it appears `spago` makes special use of the https://github.com/spacchetti/purescript-metadata repo:

- https://github.com/purescript/spago/blob/7728ce42a1c66968cce7a72dbb6ab05ea0904d9f/src/Spago/Config.hs#L106-L110
- https://github.com/purescript/spago/blob/7728ce42a1c66968cce7a72dbb6ab05ea0904d9f/src/Spago/PackageSet.hs#L193-L209

Maybe a reminder to bump the version of https://github.com/spacchetti/purescript-metadata repo should be added to either a `RELEASE_GUIDE.md` file in this repo, or to https://github.com/purescript/purescript/blob/master/RELEASE_GUIDE.md
